import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.doenca).count<[{ count: number }]>('* as count');
  if(!Number.isInteger(count) || Number(count) > 0) return;

  await knex(ETableNames.doenca).insert(doencas).then(() => {
    console.log(`# Insert table ${ETableNames.doenca}`);
  });
}

const doencas = [
  { nome: 'Oídio',                  nomeCientifico: 'Sphaerotheca Fuliginea',               sobre: 'O fungo ataca toda a parte aérea das plantas, sendo que as folhas são a parte mais afetada. Inicialmente aparecem manchas amareladas, à medida que crescem ficam recobertas por uma massa branca pulverulenta formada por micélio, conidióforos e conídios do fungo. A área atacada aumenta de tamanho podendo tomar toda a superfície foliar com a coalescência das manchas.', fonte: 'https://www.agrolink.com.br/problemas/oidio_1545.html#:~:text=O%20O%C3%ADdio%20causado%20pelo%20fungo,levando%20o%20hospedeiro%20%C3%A0%20morte.' },
  { nome: 'Ferrugem',               nomeCientifico: 'Gymnosporangium Juniperi-Virginianae', sobre: 'O ferrugem do cedro maçã é um peculiar parasita de árvores. Ocorre em ambientes onde há ambos cedros e macieiras, infectando as duas espécies. Pertence a um grupo de fungos conhecidos como "ferrugem", pois passa boa parte de seu ciclo de vida visível apenas como manchas amareladas nas folhas.', fonte: 'https://picturemushroom.com/pt/wiki/Gymnosporangium_juniperi-virginianae.html#:~:text=O%20ferrugem%20do%20cedro%20ma%C3%A7%C3%A3,como%20manchas%20amareladas%20nas%20folhas.' },
  { nome: 'Podridão Negra',         nomeCientifico: 'Physalospora Malorum',                 sobre: 'Os sintomas típicos da doença são cancros nos ramos e manchas foliares que produzem desfolha, enfraquecimento da planta e podridão dos frutos. Os primeiros sintomas nas folhas aparecem como pequenas manchas púrpuras 1-3 semanas após a queda das pétalas, evoluindo para lesões circulares de 4-5 mm de diâmetro, as margens permanecem púrpuras e o centro torna-se canela a marrom, dando-lhe a aparência de olho de rã.', fonte: 'https://www.agrolink.com.br/problemas/podridao-preta_1643.html#:~:text=Podrid%C3%A3o%20negra%20(Physalospora%20malorum)%20Culturas%20Afetadas%3A%20Ma%C3%A7%C3%A3%2C%20Pera&text=A%20podrid%C3%A3o%20negra%2C%20cujo%20anamorfo,plantas%2C%20como%20em%20p%C3%B3s%20colheita.' },
  { nome: 'Sarna',                  nomeCientifico: 'Venturia Inaequalis',                  sobre: 'Ocorrem lesões de coloração verde-oliva, isoladas ou espalhadas em ambas as superfícies das folhas, que se desenvolvem adquirindo aspecto aveludado, coloração cinza-escura e contorno aproximadamente circular.', fonte: 'https://www.agrolink.com.br/problemas/sarna-da-maca_1692.html' },
  { nome: 'Mancha de Diplocarpon',  nomeCientifico: 'Marssonina Rosae',                     sobre: 'Os sintomas apresentam-se como numerosas manchas irregulares, púrpuras ou amarronzadas, sem a coloração branca ou cinza no centro, característica das manchas-de-mycosphaerella. As manchas evoluem até atingirem 5 mm de diâmetro, coalescentes, ocupando uma área considerável da lâmina foliar. O espaço entre as manchas torna-se púrpura a vermelho-brilhante dependendo do cultivar, temperatura e outros fatores. A medida que a doença avança, as folhas geralmente tornam-se amarronzadas, secas e encarquilhadas, com aparência corticenta. No interior das lesões, na superfície adaxial das folhas, desenvolvem-se numerosos acérvulos escuros e brilhantes.', fonte: 'https://www.agrolink.com.br/problemas/mancha-de-diplocarpon_1565.html' },
  { nome: 'Mancha Isariopsis',      nomeCientifico: 'Isariopsis Clavispora',                sobre: 'O principal sintoma da doença, como o nome sugere, são manchas irregulares a angulares no limbo foliar, de 2 mm a 1 cm de diâmetro, com bordos bem definidos. Inicialmente, as manchas apresentam coloração avermelhada, passando a pardo-escura e preta. Freqüentemente, observa-se ao redor das manchas um halo amarelo-esverdeado. Na face inferior das folhas, quando o fungo frutifica, a mancha torna-se verde-olivácea.', fonte: 'https://www.agrolink.com.br/problemas/mancha-das-folhas_1674.html' },
  { nome: 'Podridão Negra',         nomeCientifico: 'Guignardia Bidwellii',                 sobre: 'O fungo ocasiona pequenas manchas circulares inicialmente de coloração acinzentada, que lentamente tornam-se castanhas. As manchas localizam-se dispersas no limbo foliar e ao coalescerem tornam-se maiores, com tonalidade castanho-clara. Com o avanço da doença, as manchas apresentam-se rodeadas por um halo de coloração castanho-escuro e sobre as manchas são visíveis os picnídios, corpos de frutificação negros do fungo, formando anéis concêntricos.', fonte: 'https://ainfo.cnptia.embrapa.br/digital/bitstream/doc/1150022/1/Bol-Tec-33-InstitutoBiologico-Thor.pdf' },
  { nome: 'Sarampo Negro',          nomeCientifico: 'Esca',                                 sobre: 'O principal sintoma é a aparição de listras intervernais nas folhas, caracterizadas pela descoloração e secagem dos tecidos ao redor das nervuras principais. Elas geralmente se mostram vermelho-escuras nas variedades vermelhas e amarelas nas variedades brancas. As folhas podem secar completamente e cair prematuramente.', fonte: 'https://plantix.net/pt/library/plant-diseases/100140/esca/' },
];
