export * as doencas from './doencas';
export * as plantas from './plantas';
export * as diagnosticos from './diagnosticos';
export * as pessoas from './pessoas';
export * as fornecedores from './fornecedores';
export * as produtos from './produtos';
export * as produtosDiagnosticos from './produtosDiagnosticos';
export * as historicoScanns from './historicoScanns';
export * as usuarios from './usuarios';
